*1. Set up local environment for #pannan2;
%let localpath=%substr(%sysget(SAS_EXECFILEPATH),1,%eval(%length(%sysget(SAS_EXECFILEPATH))-%length(%sysget(SAS_EXECFILENAME))-1));;
%inc "&localpath\Local setup pannan2.sas";

*2. Preparations;
*Clear output;
dm 'odsresults; clear';
dm 'log; clear';
filename output1 "&localpath\SAS Outputs\Investigate distributions of timing and lab values.pdf";
ods pdf file=output1;
*3. Definitions;
*4. Execute code for 24 and 6 hour windows;
proc sort data=agtx.finaldata24;
by label;
run;
proc sort data=agtx.finaldata6;
by label;
run;
title "Time between testing and transfusion for 24 hour data";
proc sgplot data=agtx.finaldata24;
where units=1;
by label;
histogram time_before / transparency=0.5 nbins=24;
histogram time_after / transparency=0.5 nbins=24;
run;
title "Time between testing and transfusion for 6 hour data";
proc sgplot data=agtx.finaldata6;
where units=1;
by label;
histogram time_before / transparency=0.5 nbins=6;
histogram time_after / transparency=0.5 nbins=6;
run;
title "Distribution of pre and post laboratory values for 24 hour data";
proc sgplot data=agtx.finaldata24;
where units=1;
by label;
histogram valuebefore / transparency=0.5;
histogram valueafter / transparency=0.5 ;
run;
title "Distribution of delta laboratory values for 24 hour data, without removing extreme values";
proc sgplot data=agtx.finaldata24;
where units=1 and extremevalue=0;
by label;
histogram deltavalue / transparency=0.5 ;
run;
title "Distribution of delta laboratory values for 24 hour data, removing < 1st percentile and > 99th percentile";
proc sgplot data=agtx.finaldata24;
where units=1 and extremevalue=0;
by label;
histogram deltavalue / transparency=0.5 ;
run;
dm 'log; print file="&localpath\Logs\Investigate distributions of timing and lab values.log" replace; ';
ods pdf close;
